#!/usr/bin/env bash
# Generate auto-generated documentation pages for mdBook.
# Run this before `mdbook build`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS_DIR="$REPO_ROOT/docs"
EXAMPLES_DIR="$REPO_ROOT/crates/vm-iucv/examples"

# --- Generate docs/README.md from root README.md ---
{
    echo "<!-- This file is auto-generated by scripts/generate-examples-docs.sh -->"
    echo "<!-- Do not edit manually — edit the root README.md instead. -->"
    echo ""
    # Convert ## headers to **bold** for mdBook sidebar cleanliness
    sed -E 's/^## (.*)/\*\*\1\*\*/' "$REPO_ROOT/README.md"
} > "$DOCS_DIR/README.md"

# --- Generate docs/EXAMPLES.md from example doc comments ---
{
    echo "<!-- This file is auto-generated by scripts/generate-examples-docs.sh -->"
    echo "<!-- Do not edit manually — edit the doc comments in the example .rs files instead. -->"
    echo ""
    echo "# Examples"

    for example in "$EXAMPLES_DIR"/*.rs; do
        [ -f "$example" ] || continue
        name="$(basename "$example" .rs)"

        echo ""
        echo "## $name"
        echo ""

        # Extract //! doc comment lines, stripping the //! prefix.
        # Also strip the leading "# Title" line (the ## name heading already serves).
        # Use -E for portable extended regex (works on both macOS and Linux).
        sed -nE 's|^//! ?||p' "$example" | sed -E '1{/^# /d;}'

        echo ""
        echo '```sh'
        echo "cargo run -p vm-iucv --example $name --features examples"
        echo '```'
        echo ""
        echo "---"
    done
} > "$DOCS_DIR/EXAMPLES.md"

echo "Generated docs/README.md and docs/EXAMPLES.md"
